name: Deploy Content to securityoperations-workspace [016b433b-a1f4-4ba3-990e-5ea252ef17b8]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-016b433b-a1f4-4ba3-990e-5ea252ef17b8.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on:
  push:
    branches: [ master ]
    paths:
    - '**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '.github/workflows/sentinel-deploy-016b433b-a1f4-4ba3-990e-5ea252ef17b8.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'secops'
      workspaceName: 'securityoperations-workspace'
      workspaceId: '53b7ac85-9b7d-4e50-9a89-d7780a86e303'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzureCloud'
      contentTypes: 'HuntingQuery,Parser'
      branch: 'master'
      sourceControlId: '016b433b-a1f4-4ba3-990e-5ea252ef17b8'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
    permissions:
      contents: write
      id-token: write # Require write permission to Fetch an OIDC token.

    steps:
    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_016b433ba1f44ba3990e5ea252ef17b8 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_016b433ba1f44ba3990e5ea252ef17b8 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_016b433ba1f44ba3990e5ea252ef17b8 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 1 failed
      if: ${{ steps.login1.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/login@v2
      if: ${{ steps.login1.outcome=='failure' }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_016b433ba1f44ba3990e5ea252ef17b8 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_016b433ba1f44ba3990e5ea252ef17b8 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_016b433ba1f44ba3990e5ea252ef17b8 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 2 failed
      if: ${{ steps.login2.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/login@v2
      if: ${{ steps.login2.outcome=='failure'  }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_016b433ba1f44ba3990e5ea252ef17b8 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_016b433ba1f44ba3990e5ea252ef17b8 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_016b433ba1f44ba3990e5ea252ef17b8 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy Content to Microsoft Sentinel
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}//.github/workflows/azure-sentinel-deploy-016b433b-a1f4-4ba3-990e-5ea252ef17b8.ps1